name: iRadio
options:
  bundleIdPrefix: net.downstreamtech
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: ""
    CODE_SIGNING_REQUIRED: "NO"

targets:
  iRadio:
    type: application
    platform: iOS
    sources:
      - iRadio
    settings:
      base:
        INFOPLIST_FILE: iRadio/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: net.downstreamtech.iradio
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        UIBackgroundModes:
          - audio
    entitlements:
      path: iRadio/iRadio.entitlements
