name: "Bug Report"
description: Report a problem
title: "[BUG] "
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
    validations:
      required: true
