name: "Feature Request"
description: Suggest improvement
title: "[FEATURE] "
labels: ["enhancement"]

body:
  - type: textarea
    id: proposal
    attributes:
      label: Describe the feature
    validations:
      required: true
