-- 006_seed_genres_comprehensive.sql — Comprehensive music genre seed
-- Idempotent: ON CONFLICT DO NOTHING prevents duplicates

INSERT INTO categories (name, type) VALUES
  -- Core / broad genres
  ('Rock','music'),
  ('Pop','music'),
  ('Country','music'),
  ('R&B','music'),
  ('Hip Hop','music'),
  ('Jazz','music'),
  ('Blues','music'),
  ('Classical','music'),
  ('Electronic','music'),
  ('Folk','music'),
  ('Reggae','music'),
  ('Latin','music'),
  ('Gospel','music'),
  ('Christian','music'),
  ('Metal','music'),
  ('Alternative','music'),
  ('Indie','music'),
  ('Funk','music'),
  ('Soul','music'),
  ('World','music'),
  ('Easy Listening','music'),
  ('New Age','music'),
  ('Disco','music'),
  ('Punk','music'),
  ('Singer-Songwriter','music'),

  -- Rock sub-genres
  ('Classic Rock','music'),
  ('Soft Rock','music'),
  ('Hard Rock','music'),
  ('Progressive Rock','music'),
  ('Psychedelic Rock','music'),
  ('Southern Rock','music'),
  ('Garage Rock','music'),
  ('Surf Rock','music'),
  ('Grunge','music'),
  ('Post-Rock','music'),
  ('Stoner Rock','music'),
  ('Glam Rock','music'),
  ('Art Rock','music'),

  -- Metal sub-genres
  ('Heavy Metal','music'),
  ('Thrash Metal','music'),
  ('Death Metal','music'),
  ('Black Metal','music'),
  ('Doom Metal','music'),
  ('Power Metal','music'),
  ('Symphonic Metal','music'),
  ('Nu Metal','music'),
  ('Metalcore','music'),
  ('Progressive Metal','music'),

  -- Pop sub-genres
  ('Synth Pop','music'),
  ('Electropop','music'),
  ('Indie Pop','music'),
  ('Dream Pop','music'),
  ('K-Pop','music'),
  ('J-Pop','music'),
  ('Teen Pop','music'),
  ('Bubblegum Pop','music'),
  ('Chamber Pop','music'),
  ('Power Pop','music'),
  ('Britpop','music'),

  -- Electronic / Dance
  ('House','music'),
  ('Techno','music'),
  ('Trance','music'),
  ('Drum and Bass','music'),
  ('Dubstep','music'),
  ('Ambient','music'),
  ('EDM','music'),
  ('Downtempo','music'),
  ('Trip Hop','music'),
  ('Industrial','music'),
  ('Synthwave','music'),
  ('Chillwave','music'),
  ('Lo-Fi','music'),
  ('Garage','music'),
  ('Breakbeat','music'),
  ('Hardstyle','music'),
  ('Electro','music'),
  ('Deep House','music'),
  ('Progressive House','music'),
  ('Tropical House','music'),
  ('Future Bass','music'),
  ('Chillout','music'),

  -- Hip Hop / Rap sub-genres
  ('Rap','music'),
  ('Trap','music'),
  ('Boom Bap','music'),
  ('Conscious Hip Hop','music'),
  ('Southern Hip Hop','music'),
  ('West Coast Hip Hop','music'),
  ('East Coast Hip Hop','music'),
  ('Drill','music'),
  ('Grime','music'),
  ('Lo-Fi Hip Hop','music'),
  ('Mumble Rap','music'),

  -- R&B / Soul sub-genres
  ('Contemporary R&B','music'),
  ('Neo Soul','music'),
  ('Motown','music'),
  ('Quiet Storm','music'),
  ('Rhythm and Blues','music'),

  -- Jazz sub-genres
  ('Smooth Jazz','music'),
  ('Bebop','music'),
  ('Swing','music'),
  ('Cool Jazz','music'),
  ('Free Jazz','music'),
  ('Fusion','music'),
  ('Latin Jazz','music'),
  ('Acid Jazz','music'),
  ('Bossa Nova','music'),
  ('Big Band','music'),
  ('Vocal Jazz','music'),

  -- Blues sub-genres
  ('Delta Blues','music'),
  ('Chicago Blues','music'),
  ('Electric Blues','music'),
  ('Blues Rock','music'),
  ('Boogie-Woogie','music'),
  ('Rhythm and Blues','music'),

  -- Country sub-genres
  ('Country Pop','music'),
  ('Bluegrass','music'),
  ('Outlaw Country','music'),
  ('Country Rock','music'),
  ('Americana','music'),
  ('Honky-Tonk','music'),
  ('Western Swing','music'),
  ('Nashville Sound','music'),
  ('Alt-Country','music'),
  ('Red Dirt','music'),

  -- Folk sub-genres
  ('Indie Folk','music'),
  ('Folk Rock','music'),
  ('Celtic','music'),
  ('Acoustic','music'),
  ('Traditional Folk','music'),
  ('Contemporary Folk','music'),
  ('Folk Pop','music'),

  -- Latin sub-genres
  ('Salsa','music'),
  ('Bachata','music'),
  ('Reggaeton','music'),
  ('Cumbia','music'),
  ('Merengue','music'),
  ('Tango','music'),
  ('Samba','music'),
  ('Mariachi','music'),
  ('Tropicalia','music'),
  ('Latin Pop','music'),
  ('Latin Rock','music'),
  ('Bolero','music'),
  ('Son','music'),
  ('Norteño','music'),
  ('Banda','music'),
  ('MPB','music'),

  -- Caribbean / Island
  ('Dancehall','music'),
  ('Ska','music'),
  ('Calypso','music'),
  ('Soca','music'),
  ('Dub','music'),
  ('Reggae Fusion','music'),
  ('Rocksteady','music'),

  -- African
  ('Afrobeat','music'),
  ('Afropop','music'),
  ('Highlife','music'),
  ('Amapiano','music'),
  ('Kwaito','music'),
  ('Afrobeats','music'),
  ('Mbalax','music'),
  ('Soukous','music'),

  -- Asian
  ('OPM','music'),
  ('Kundiman','music'),
  ('Harana','music'),
  ('Pinoy Rock','music'),
  ('Pinoy Pop','music'),
  ('C-Pop','music'),
  ('Bollywood','music'),
  ('Bhangra','music'),
  ('Enka','music'),
  ('City Pop','music'),
  ('Mandopop','music'),
  ('Cantopop','music'),
  ('Thai Pop','music'),
  ('Gamelan','music'),

  -- Punk sub-genres
  ('Pop Punk','music'),
  ('Post-Punk','music'),
  ('Hardcore Punk','music'),
  ('Emo','music'),
  ('Ska Punk','music'),
  ('Anarcho-Punk','music'),
  ('Crust Punk','music'),

  -- Other
  ('Soundtrack','music'),
  ('Film Score','music'),
  ('Video Game Music','music'),
  ('Anime','music'),
  ('Musical Theater','music'),
  ('Opera','music'),
  ('Choral','music'),
  ('A Cappella','music'),
  ('Spoken Word','music'),
  ('Comedy','music'),
  ('Novelty','music'),
  ('Children','music'),
  ('Holiday','music'),
  ('Christmas','music'),
  ('Worship','music'),
  ('Praise','music'),
  ('Instrumental','music'),
  ('Experimental','music'),
  ('Avant-Garde','music'),
  ('Noise','music'),
  ('Shoegaze','music'),
  ('Post-Punk Revival','music'),
  ('Britpop','music'),
  ('Baroque Pop','music'),
  ('Neofolk','music'),
  ('Dark Wave','music'),
  ('Gothic','music'),
  ('Ethereal Wave','music'),
  ('Ambient','music'),

  -- Crossover / Fusion
  ('Jazz Funk','music'),
  ('Jazz Rap','music'),
  ('Country Rap','music'),
  ('Reggae Rock','music'),
  ('Rap Rock','music'),
  ('Rap Metal','music'),
  ('Folk Metal','music'),
  ('Celtic Punk','music'),
  ('Psychedelic Soul','music'),
  ('Electro Swing','music'),
  ('Future Funk','music'),

  -- Modern / Emerging
  ('Bedroom Pop','music'),
  ('Hyperpop','music'),
  ('Vaporwave','music'),
  ('Phonk','music'),
  ('Dark Trap','music'),
  ('Cloud Rap','music'),
  ('Emo Rap','music'),
  ('Afro Fusion','music'),
  ('Alté','music'),
  ('Neo-Classical','music'),
  ('Post-Classical','music'),
  ('Witch House','music'),
  ('Chiptune','music')

ON CONFLICT (name) DO NOTHING;

-- Reset sequence to avoid duplicate key errors when creating new categories
SELECT setval('categories_id_seq', (SELECT COALESCE(MAX(id), 1) FROM categories));
